### ISSUE TITLE
Fix colors of neo6502 logo

### ISSUE THREAD

**Issue by astralaster** [paulscottrobson/neo6502-firmware#163]
The colors of the neo6502 logo on bootup are meant to be different then they look right now. It seems to be limited by the console palette right now.

![image](https://github.com/paulscottrobson/neo6502-firmware/assets/1084035/b2448d8a-3f64-4d4f-a2b2-d73195f2a7ea)

**Comment by paulscottrobson** [comment]
Okay .... I'll try to figure it out .... this is harassment :(

**Comment by paulscottrobson** [comment]
So what colours do you want what .... give me some RGB values and I'll make it work.

That's what I liked about coding for the RCA Studio 2. No colour arguments ...

**Comment by astralaster** [comment]
> So what colours do you want what .... give me some RGB values and I'll make it work.
> 
> That's what I liked about coding for the RCA Studio 2. No colour arguments ...

The colors in the image above are the wanted ones. #ff00ff for the spiral and #00ffff for the text.

**Comment by paulscottrobson** [comment]
No problem, I think.
