### ISSUE TITLE
vectors.py does not ignore comments when searching through file

### ISSUE THREAD

**Issue by ulften** [paulscottrobson/neo6502-firmware#198]
For maybe the wrong reasons, I decided to move ControlPort (and DEFAULT_PORT) to a different address.  Unfortunately, I kept the original lines as comments when  I made my changes. This resulted in a rather hard issue to track down. Eventually, I realized that the kernel/scripts/vectors.py script, which is used to extract the DEFAULT_PORT from firmware/common/include/interface/memory.h picked up the old commented out value, rather than my new address that I was defined on the next line.

It would be good if vectors.py skipped over comments.

/Ulf

**Comment by paulscottrobson** [comment]
Good idea :)
