### ISSUE TITLE
ESC key

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#199]
ESC key can be useful in apps, but it's impossible to use it in emulator. 
Can we use another key to force close the emulator window? 
Maybe F12, ctrl-Q or Ctrl-ESC ?

**Comment by paulscottrobson** [comment]
Ctrl-ESC does actually work :)

The emulator uses the same skeleton program I've had for a while - there's a reason the Commander X16 debugger looks near identical, I wrote it.  This uses various function keys for set breakpoint and single step, and ESC to exit.  The machine itself uses both, so it's set up if you do Ctrl-ESC it behaves like you just do ESC.
