### ISSUE TITLE
Documentation order mixed up ?

### ISSUE THREAD

**Issue by paulscottrobson** [paulscottrobson/neo6502-firmware#234]
I've merged the new API documentation, which is much better, and am removing things from the manual as they become unneccessary.

However, there seems to be a page ordering issue ? On mine it gets to 5/4 then has a section on console codes, and then section 5 continues later. Is this a bug ?

**Comment by bill-auger** [comment]
no, the comment in dispatch.config explains how to manage that - as table rows and text are added or removed, tables may grow to be larger than will fit on a single page, or may shrink and pull the following table onto the same page with it, where they will not fit on one page together - when that happens, one of the tables (or image or whatever) will "float" to an unexpected location - to make the table fit again, adjust the page-breaks on the GROUP line - if you show me the new dispatch.config, i will verify that is what happened
