### ISSUE TITLE
Emulator. Pressing F1 key erases existing program.

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#247]
As the title indicates, Pressing the F1 key erases the existing Basic program and displays "Welcome to NeoBasic".  Workaround is to issue 'OLD".

**Comment by paulscottrobson** [comment]
This is deliberate ; it's part of the emulator ; F1 is the reset key :) If you don't want to use the debugger keys use 'keys' on the command line.
