### ISSUE TITLE
Check dependency errors

### ISSUE THREAD

**Issue by giovannipozzobon** [paulscottrobson/neo6502-firmware#303]
In the latest update, dependency checking has been introduced. The following lines generate errors in the Mac OSX environment. 
	@python -c 'from importlib.metadata import version ; pkg="gitpython" ; print("python-%s: %s" % (pkg , version(pkg)))'
	@python -c 'from importlib.metadata import version ; pkg="pillow"    ; print("python-%s: %s" % (pkg , version(pkg)))'

They can be modified as follows:
	@python3 -c 'from importlib.metadata import version ; pkg="gitpython" ; print("python-%s: %s" % (pkg , version(pkg)))'
	@python3 -c 'from importlib.metadata import version ; pkg="pillow"    ; print("python-%s: %s" % (pkg , version(pkg)))'

Also, because the command is already included in the check:
	@python3     --version

**Comment by paulscottrobson** [comment]
Thanks Giovanni, putting this one through as I write.
