### ISSUE TITLE
Implement Text Terminal-type Video Mode for CP/M-65, and "serious" software

### ISSUE THREAD

**Issue by SanPollo** [paulscottrobson/neo6502-firmware#375]
Please implement a high resolution text-only terminal-style mode of 80x25 characters, so that programs ported to CP/M-65 from other platforms, and "serious" type software can be used on the Neo6502.

To save RAM, this could be mono, as CP/M software does not require colour.

**Comment by paulscottrobson** [comment]
It's been considered and is difficult at present. The most likely implementation is a scrolling window on a larger screen, some C64 word processors did this. The system does actually support an 80x25 console internally ; it's displaying it that's the problem. I'll close it for now, but it is under active consideration (CPM/65 would benefit from it)
