### ISSUE TITLE
Provide additional commands for  file operations

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#44]
Hi Paul,
Thanks for the excellent Neo BASIC implementation. I just started playing with it. It looks like we can issue a CAT command to see root directory contents of the attached device (using USB version). It would be useful to have CD and MKDIR commands as well. 
Keep up the good work.
P.S. Not sure how to browse sub directories at the moment.

**Comment by paulscottrobson** [comment]
You can't :) It's something that will be added

**Comment by leventp** [comment]
As you indicated, it would be nice to implement a MOS like interface similar to the one developed for Agon Light 2.

**Comment by paulscottrobson** [comment]
This will be delayed until @davidgiven 's file system routines for CPM/65 are stable. It may even be done by CPM/65 itself as an option.
