### ISSUE TITLE
toupper(x$) tolower(x$) ?

### ISSUE THREAD

**Issue by erlendnagel** [paulscottrobson/neo6502-firmware#455]
I would love to have a toupper and tolower function in neobasic so I could just write:
a$=toupper(i$)
if a$="Y"
 ....
instead of 
call toupper(a$,i$)

unless of course I am missing something

**Comment by erlendnagel** [comment]
Oops: Not an issue, but for discussion. Apologies.

**Comment by paulscottrobson** [comment]
Okay :)

**Comment by paulscottrobson** [comment]
Will be upper$() and lower$() the $ is because functions that return strings have that $ in there.
