### ISSUE TITLE
Blitter overwrites the data source

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#459]
I don't know if it's a bug or not, but the blitter copy can't move data "forward" when areas overlap. Let me use an example. Imagine that we have such data in memory:
1111222233334444

and we make a blit "backwards" : 
BlitterCopy(4,0,12) - and we get
2222333344444444 - and this is ok.

but when we try to move data forward : 
BlitterCopy(0,4,12) - we get
1111111111111111 - not ok, because the source data gets overwritten

I understand that the blitter is not smart enough to perform a rewrite from the end of the data in such a case, so as not to overwrite it.

Pascal's "Move" handled this seamlessly, which is why I ask

**Comment by paulscottrobson** [comment]
The blitter is rubbish :) It was slung together fairly quickly so you could do that internal copying. It's not suitable for scrollling. I will improve the straight copy, though I would really like it to be able to do things like copy rectangular areas and so on.
