### ISSUE TITLE
mouse wheel does not work in emulator

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#468]
Mouse wheel reading does not work in emulator, at least in Windows and WSL.

**Comment by paulscottrobson** [comment]
Ah, I forgot about it :)

**Comment by paulscottrobson** [comment]
I cannot make it work on my hardware, it is sending through a 3 entry packet even though I have a mouse wheel. How does the wheel parameter behave on real world hardware ; what's the start value, does it increment or decrement on the mouse being scrolled down (e.g. towards the user)

**Comment by bocianu** [comment]
On the real hardware starting value is 0, and it decrements on scrolling down (jumping to 255 and getting down on every consecutive roll), and it increments on scroll up.
