### ISSUE TITLE
Sound  command 'sfx' behavior

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#47]
My observations with 'sfx'. Looks like all sfx statements are put onto a queue and only the last one played.
Not sure if this is the expected behavior. Below is the code tested:

10 sfx 0,0
20 sfx 0,1
30 sfx 0,2

Only sfx 0,2 gets executed.

**Comment by paulscottrobson** [comment]
This is deliberate. When writing Galaxians in BASIC I found I was always clearing the queue before SFX commands. This actually makes sense as most of them are in response to events in the game, so if you queue them they won't be coincident with the trigger.

I couldn't think of a usage for these queuing occasionally chaining two together. So I decided to clear the queue always for SFX. 

If you want to wait, the following code will wait for the sound effect to compete, 

`repeat:until notes(0) = 0`
