### ISSUE TITLE
Blitter broken since 22 May

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#513]
Merge of the new blitter from @bcampbell broke the API.
I cannot reproduce the same functionality I had on the previous one on this new one.
My two programs have stopped working.

**Comment by paulscottrobson** [comment]
That may be my fault. I did give @bcampbell a fairly free hand in that as when he changed it it was very new beyond the very limited simple copy. Is it basically not working *at all* or is it something specific ?

**Comment by bcampbell** [comment]
> Merge of the new blitter from @bcampbell broke the API. I cannot reproduce the same functionality I had on the previous one on this new one. My two programs have stopped working.

Do you mean "Simple Blit Copy" (Function 2) or "Complex Blit Copy" (Function 3)?

The Simple Blit should have stayed the same, but the Complex Blit did change. I figured it had only been out for a week or so, so there probably wasn't anything relying on it (famous last words :-).
There was a bunch of stuff the API didn't support that I thought it would benefit from, so I went ahead and changed it.

What are you doing with it? The new complex blit _should_ be able to do everything the old one could, even if it's a bit of an arse updating the calls...

**Comment by bocianu** [comment]
Yes, I was using function 3 :D 
Short description what was I doing I what I cannot achieve right now:

Previous implementation was able to blit rectangles using this structure:
![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/895c2cd0-794c-41fb-b906-1bdcc5d5f42a)

And at start of my program I was painting "bricks" on screen and copying them to GFX memory using blitter and this settings below:

![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/5ed69529-e506-45d9-9cc2-8306689c6052)

So in gfx memory every brisk was a linear block.
And then in game using the same settings I was blitting it back to screen.
And it worked flawlessly. 

And then the merge came, and I tried to use a new improved blitter to do the same, so new block structure was defined like:

![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/81fb2081-5610-4423-81e5-25b4fe3ba100)

and tried to achieve the same thing:

![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/2f69cb70-6ce7-4573-9a44-93a57bbd694a)

And it blits only the first line of the image. Maybe the problem lies here:

![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/75eb84e2-c4ca-4246-92cf-488333cd97f1)

if width is not used in target, I cannot define different shape as an output. If source is linear I cannot make destination narrower rectangle?

**Comment by bcampbell** [comment]
OK, I think something like this should work:
```
blockGFX.format := 0
blockGFX.stride := BRICK_WIDTH;
blockGFX.width := BRICK_WIDTH;
blockGFX.height := BRICK_HEIGHT;

blockScr.format := 0
blockScr.stride := 320;
```

Stride is the number of bytes between the start of each line.
So for your linear source brick, the stride is the same as the byte width of your image.
For the screen, it's 320 bytes between the start of each line. 
The stride allows all kinds of tricks:
You could use a negative source stride to draw your tile flipped vertically.
Or you could use a zero source stride to draw the same source line repeatedly.

BTW, if your source brick image is only 16 colours, you could pack 2 pixels into each byte and the blit operation will unpack it for you on the fly. The changed lines would be:
```
blockGFX.format := 1   // 2 pixels per byte
blockGFX.stride := BRICK_WIDTH/2;
```
Or if you've got monochrome source images you can pack 8 pixels/byte:
```
blockGFX.format := 2   // mono (8 pixels per byte)
blockGFX.stride := BRICK_WIDTH/8;
```

When you've got a total 64KB of RAM to play with, I find 8 bit-per-pixel graphics suddenly seem to take up an awful lot of space :-)
Hope this helps!

**Comment by bocianu** [comment]
ok, so stride was not an 1:1 equivalent of the stepoffset 😄 
Now, after the changes you suggested it works! thanks.
And the possibilities are much wider now. 
We can close the issue now.
