### ISSUE TITLE
API File Read succeeds on write-only file.

### ISSUE THREAD

**Issue by PeteGollan** [paulscottrobson/neo6502-firmware#546]
I open a file using API File Open in mode 1 (write only) and after writing some data to the file, attempt to read it using API File Read. This should fail as the file was opened in mode 1 (write-only), but the read succeeds. I haven't tested other permutations (e.g. writing a read-only file). I don't have a clean example to show as this came up in testing my CC65 file I/O drivers. The CC65 file I/O abstraction layer does not enforce the read/write-only flags, so it is up to either the drivers or the underlying hardware (in this case, the Neo6502 API).

**Comment by paulscottrobson** [comment]
I've decided against implementing now this because of the way the I/O system is done. This really should be in common code, but the code is split in emulator / firmware too specifically.
