### ISSUE TITLE
Requst : Screen modes, 80 Columns, etc

### ISSUE THREAD

**Issue by snakebyte69** [paulscottrobson/neo6502-firmware#553]
Ability to change screen mode
80 Columns for CP/M65 and other resolutions

**Comment by paulscottrobson** [comment]
It's quite difficult and has been assigned low priority. I did experiment with trying to change the DVI driver code but I couldn't get anywhere. We don't have the memory for a 80 column graphic display - only 264k in the RP2040 has to do everything - but a colour text screen should be doable. The code is actually designed to have different screen modes but it hasn't happened to date.

**Comment by paulscottrobson** [comment]
Closed for now.
