### ISSUE TITLE
API FILE STAT operates differently between emulator and hardware when target is a directory

### ISSUE THREAD

**Issue by PeteGollan** [paulscottrobson/neo6502-firmware#563]
When API FILE STAT is called with an existing DIRECTORY name, it fails on the emulator, but succeeds on the hardware. Tested on v0.33 and v0.36 firmware. It should be consistent between emulator and hardware. (I'd prefer if it succeeded with both directories and files so I can check the directory bit to distinguish between directories and files, but I don't know if this breaks existing code elsewhere).

**Comment by paulscottrobson** [comment]
The hardware is definitive, usually, so it should work on the emulator as well.
