### ISSUE TITLE
Feature request - listbasic.zip

### ISSUE THREAD

**Issue by OrangeBox72** [paulscottrobson/neo6502-firmware#573]
It would be pretty cool if there was a command-line parameter for **listbasic.zip** that would omit the line numbers in the **<file>.bsc** output.

example:

*CURRENT WAY*
\> python3 listbasic.zip myCode.bas
\> cat myCode.bsc
   10 cls
   20 print "hello"

*REQUEST*
\> python3 listbasic.zip -nollinenumbers myCode.bas
\> cat myCode.bsc
   cls
   print "hello"

**Comment by paulscottrobson** [comment]
Good idea. Never thought of it.
