### ISSUE TITLE
executing binary files in emulator and basic equivalent 

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#60]
It would be nice to be able execute binary files not only basic tokenized,
Like this:
**neo.exe myexecutable.bin@2000 exec**

Now every time I load a new binary I have to type "sys $2000" to launch my program.

**Comment by bocianu** [comment]
or maybe even new parameter when you can specify run address, like this:
**neo.exe myexecutable.bin@2000 run@20FC**

**Comment by autismuk** [comment]
Shall do. I'm away at present. Also needs to be doable from the basic command line

**Comment by paulscottrobson** [comment]
Supports with run@20fc syntax as suggested.
