### ISSUE TITLE
FALSE and TRUE constants giving ODD results

### ISSUE THREAD

**Issue by jewettg** [paulscottrobson/neo6502-firmware#608]
Some odd behavior out of using the TRUE and FALSE constants.

```
print not FALSE
00
print not TRUE
0-1
```

What it should do?   
```
print not FALSE
-1
print not TRUE
0
```

..and using true and false numbers (values) also gives odd results.
```
print not -1
-1
print not 00
00
```

**Comment by paulscottrobson** [comment]
It's actually not a bug. It's arguable it should be an enhancement. There is no NOT keyword so it thinks it's a variable, so it's printing out the value of 'not' and not-1 is an expression.

I'll close this and add NOT
