### ISSUE TITLE
Allow custom turtle sprites

### ISSUE THREAD

**Issue by bocianu** [paulscottrobson/neo6502-firmware#63]
Maybe I'm doing something wrong, but I'm unable to replace turtle sprite using API call  9,1.
My sprite is 16x16, index 0. GFX Resource is properly loaded because I can use DrawImage to put in on the screen.
But when I select it (on P0) in turtle Init function, the default sprite is not replaced. 
I tried indexing it as 0, 128, 192 - nothing works for me.

**Comment by paulscottrobson** [comment]
Currently there is no option to have a custom turtle. It's not a bad idea though so I will change this appropriately.

**Comment by bocianu** [comment]
Api documentation says it is custom sprite option :) that's why I had asked.
![image](https://github.com/paulscottrobson/neo6502-firmware/assets/2974998/c464c81e-d42c-453f-872a-f9aeb6a65883)

**Comment by paulscottrobson** [comment]
Unclear. What it means is that's the sprite to use for the turtle. It co-opts one for its own use. I'll improve it.
