### ISSUE TITLE
Implement RENUMBER

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#64]
It would be nice to have the following commands in NeoBASIC for making editing process easier and more efficient:

- AUTO 
- RENUMBER  (As noted in the current BASIC document no need to renumber legacy GOTO and GOSUB)
- DELETE 

I suggest to use the syntax defined in BBC BASIC.

**Comment by paulscottrobson** [comment]
Not sure about AUTO ; I have a concept for a screen editor under BASIC. RENUMBER and DELETE are certainly worh doing.

**Comment by paulscottrobson** [comment]
Decided against AUTO.

**Comment by paulscottrobson** [comment]
DELETE implemented

**Comment by paulscottrobson** [comment]
RENUMBER implemented, does not handle GOTO or GOSUB.
