### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#74]
This is a would be nice enhancement. BBC Basic provides some error handling functionality to debug programs. For example:

ON ERROR PROCxxx
 and
ERR (error number encountered)
ERL (line number on which error occurred)

In this way, any error can be trapped and handled accordingly. Any similar error handling in NeoBASIC would be a nice addition.

**Comment by paulscottrobson** [comment]
Probably not feasible. Calling code on an error is doable, but the question would be what state do you go back to. If you did call someproc(1/0) it would generate a division by zero, then what do you do afterwards ?

**Comment by leventp** [comment]
I thought Error handling would be handled by the user defined procedure and program would exit anyway. Just another way of displaying error messages by making them more context oriented. However, not a big deal.

**Comment by paulscottrobson** [comment]
Ah, now that is perhaps doable. I'll think about it.

**Comment by paulscottrobson** [comment]
**ON ERROR** <do this, can be anything>
**ERR** returns the error number, which aren't documented.
**ERL** returns the line number

**Comment by paulscottrobson** [comment]
Implemented. Effectively it's doing a GOTO to the code, so it may be recoverable within reason.
