### ISSUE TITLE
Release 0.10.0 contains 0.9.0 release binaries

### ISSUE THREAD

**Issue by leventp** [paulscottrobson/neo6502-firmware#80]
I am getting Release 0.9.0 after installing the firmware on the device and emulator.

**Comment by paulscottrobson** [comment]
That's because I forgot to update it. I haven't found a way of importing it into the build automatically. It is 0.10.0. My bad !

**Comment by leventp** [comment]
No worries. Yes the code is 0.10.0 release:)
