### ISSUE TITLE
"Cross-Development" documentation issues

### ISSUE THREAD

**Issue by bill-auger** [paulscottrobson/neo6502-firmware#95]
the "Cross-Development" wiki has a confusing example
> ../bin/neo build/basic.bin@800  build/tokenised.dat@page exec

firstly, it assumes that the user is in some sub-directory of the source tree; but does not mention which - that immediately makes the ../ and build/ references ambiguous

but secondly, there is no directory in the source tree in which that example will actually work; because basic.bin is only present in the bin/ directory

```
$ ../bin/neo build/basic.bin@800  build/tokenised.dat@page exec
Load build/basic.bin to 800
Bad file build/basic.bin
```
```
$ find -name basic.bin
./bin/basic.bin
```

the reference to 'build/tokenised.dat' is also ambiguous - i have no such file - presumably, tokenised.dat is intended to be a placeholder for any tokenized basic file - if so i would suggest clarifying that, eg:

> ../bin/neo build/basic.bin@800 SOME_TOKENIZED_BASIC_FILE@page exec

```
$ ./bin/neo bin/basic.bin@800 build/tokenised.dat@page exec
Load bin/basic.bin to 800
Load build/tokenised.dat to 3900
Bad file build/tokenised.dat
```
```
$ find -name tokenised.dat
```
```
$ find -type d -name build
./basic/images/build
./basic/build
./firmware/build
./kernel/build
```
```
$ ls $(find -type d -name build)
./basic/build:

./basic/images/build:

./firmware/build:
CMakeFiles/  _deps/  elf2uf2/  generated/  pico-sdk/  pioasm/  sources/  CMakeCache.txt  cmake_install.cmake  Makefile

./kernel/build:
kernel.bin  kernel_binary.h  kernel.lst  _vectors.inc
```

however, these failures (eg: the missing  'build/tokenised.dat') could be due to the build failure (#94) - perhaps this issue would be resolved by a complete re-build

**Comment by paulscottrobson** [comment]
It's out of date. BASIC is loaded by default anyway. I think it's a hangover from the original being also used for BASIC development.  When I wrote the first couple of sample games it produced a slew of minor bugs in BASIC, so it was set up to assemble and BASIC develop both at the same time, so rather than rebuilding the emulator I just loaded the current image in.
