### ISSUE TITLE
intermittent audio buffer under-runs

### ISSUE THREAD

**Issue by bill-auger** [paulscottrobson/neo6502-firmware#97]
this only happens approximately once every 20 starts of the emulator; so ive not had the patience to try catching it under a debugger - IIRC, it happens even if no code accesses the sound routines (eg: even launching BASIC) - that is, presuming that BASIC does not play any sounds upon launch - if it does, that may be another bug - ive never heard sound while launching BASIC; and i can not get sound routine 8,3 (Play the startup beep) to produce sound

```
ALSA lib pcm.c:8740:(snd_pcm_recover) underrun occurred
```

so far, it appears to be harmless; but ive not run anything complex - sound effects (via sound routine 8,5) play regardless (those are the only sounds that i have tried); but it is an annoyance - it spams the console (about once per second) for a few minutes, then it slows down for a few minutes, then it apparently stops - i let it run for 15 more minutes after it stopped, with no more occurrences

**Comment by paulscottrobson** [comment]
Seems to be implementation specific. I've had this code for years (literally, the emulator and debugger framework goes back years) and I was never happy with it.  SDL2 is really set up for playing samples, not just beeping. 

I found a sample beeper that's part of Chromium https://chromium.googlesource.com/external/github.com/kripken/emscripten/+/1.35.20/tests/sdl_audio_beep.cpp which is similar - but - different, so I'll see if this can replace the framework beeper class, it's pretty much a single unit.
